// * Set Actions
export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_PROVIDER_STATUS = 'SET_PROVIDER_STATUS';

export const ENABLE_REQUEST = 'ENABLE_REQUEST';
export const ENABLE_SUCCESS = 'ENABLE_SUCCESS';
export const ENABLE_FAILURE = 'ENABLE_FAILURE';

// * Wallet
export const SET_WALLET = 'SET_WALLET';
export const SET_ADDRESS = 'SET_ADDRESS';

// * Sign actions
export const WALLET_SIGN_TRANSACTION_REQUEST =
  'WALLET_SIGN_TRANSACTION_REQUEST';
export const WALLET_SIGN_TRANSACTION_SUCCESS =
  'WALLET_SIGN_TRANSACTION_SUCCESS';
export const WALLET_SIGN_TRANSACTION_FAILURE =
  'WALLET_SIGN_TRANSACTION_FAILURE';

export const WALLET_SEND_TRANSACTION_REQUEST =
  'WALLET_SEND_TRANSACTION_REQUEST';
export const WALLET_SEND_TRANSACTION_SUCCESS =
  'WALLET_SEND_TRANSACTION_SUCCESS';
export const WALLET_SEND_TRANSACTION_FAILURE =
  'WALLET_SEND_TRANSACTION_FAILURE';

export const WALLET_SIGN_MESSAGE_REQUEST = 'SIGN_MESSAGE';
export const WALLET_SIGN_MESSAGE_SUCCESS = 'WALLET_SIGN_MESSAGE_SUCCESS';
export const WALLET_SIGN_MESSAGE_FAILURE = 'WALLET_SIGN_MESSAGE_FAILURE';

export const WALLET_SIGN_TYPED_MESSAGE_REQUEST =
  'WALLET_SIGN_TYPED_MESSAGE_REQUEST';
export const WALLET_SIGN_TYPED_MESSAGE_SUCCESS =
  'WALLET_SIGN_TYPED_MESSAGE_SUCCESS';
export const WALLET_SIGN_TYPED_MESSAGE_FAILURE =
  'WALLET_SIGN_TYPED_MESSAGE_FAILURE';

// Provider Actions
export const PROVIDER_GET_BLOCK_NUMBER = 'PROVIDER_GET_BLOCK_NUMBER';
export const PROVIDER_GET_GAS_PRICE = 'PROVIDER_GET_GAS_PRICE';
export const PROVIDER_GET_BLOCK = 'PROVIDER_GET_BLOCK';
export const PROVIDER_GET_TRANSACTION = 'PROVIDER_GET_TRANSACTION';
export const PROVIDER_GET_TRANSACTION_RECEIPT =
  'PROVIDER_GET_TRANSACTION_RECEIPT';
export const PROVIDER_ENS_RESOLVE_NAME = 'PROVIDER_ENS_RESOLVE_NAME';
export const PROVIDER_ENS_LOOKUP_ADDRESS = 'PROVIDER_ENS_LOOKUP_ADDRESS';
export const PROVIDER_CALL_REQUEST = 'PROVIDER_ENS_LOOKUP_ADDRESS';

// Contract Execution (https://docs.ethers.io/ethers.js/html/api-providers.html#contract-execution)
export const PROVIDER_CALL = 'PROVIDER_CALL';
export const PROVIDER_ESTIMATE_GAS = 'PROVIDER_ESTIMATE_GAS';
export const PROVIDER_SEND_TRANSACTION = 'PROVIDER_SEND_TRANSACTION';

// Contact State (https://docs.ethers.io/ethers.js/html/api-providers.html#contract-state)
export const PROVIDER_GET_CODE = 'PROVIDER_GET_CODE';
export const PROVIDER_GET_STORAGE_AT = 'PROVIDER_GET_STORAGE_AT';
export const PROVIDER_GET_LOGS = 'PROVIDER_GET_LOGS';

// Events (https://docs.ethers.io/ethers.js/html/api-providers.html#events)
export const PROVIDER_EVENT_ON = 'PROVIDER_EVENT_ON';
export const PROVIDER_EVENT_ONCE = 'PROVIDER_EVENT_ONCE';
export const PROVIDER_EVENT_REMOVE_LISTENER = 'PROVIDER_EVENT_REMOVE_LISTENER';
export const PROVIDER_EVENT_REMOVE_ALL_LISTENERS =
  'PROVIDER_EVENT_REMOVE_ALL_LISTENERS';
export const PROVIDER_EVENT_LISTENER_COUNT = 'PROVIDER_EVENT_LISTENER_COUNT';
export const PROVIDER_EVENT_RESET_BLOCKS = 'PROVIDER_EVENT_RESET_BLOCKS';

// Waiting for Transaction (https://docs.ethers.io/ethers.js/html/api-providers.html#waiting-for-transactions)
export const PROVIDER_WAIT_FOR_TRANSACTION = 'PROVIDER_WAIT_FOR_TRANSACTION';

// Etherscan (https://docs.ethers.io/ethers.js/html/api-providers.html#provider-specific-extra-api-calls)
export const PROVIDER_ETHERSCAN_PRICE = 'PROVIDER_ETHERSCAN_PRICE';
export const PROVIDER_ETHERSCAN_GET_HISTORY = 'PROVIDER_ETHERSCAN_GET_HISTORY';

// JSON RPC Provider
export const PROVIDER_JSON_RPC_PROVIDER_SEND = 'PROVIDER_JSON_RPC_SEND';
export const PROVIDER_JSON_RPC_PROVIDER_LIST_ACCOUNT =
  'PROVIDER_JSON_RPC_PROVIDER_LIST_ACCOUNT';
export const PROVIDER_JSON_RPC_PROVIDER_GET_SIGNER =
  'PROVIDER_JSON_RPC_PROVIDER_GET_SIGNER';

// JSON RPC Signer
export const PROVIDER_JSON_RPC_SIGNER_PROVIDER =
  'PROVIDER_JSON_RPC_SIGNER_PROVIDER';
export const PROVIDER_JSON_RPC_SIGNER_GET_ADDRESS =
  'PROVIDER_JSON_RPC_SIGNER_GET_ADDRESS';
export const PROVIDER_JSON_RPC_SIGNER_GET_BALANCE =
  'PROVIDER_JSON_RPC_SIGNER_GET_BALANCE';
export const PROVIDER_JSON_RPC_SIGNER_GET_TRANSACTION_COUNT =
  'PROVIDER_JSON_RPC_SIGNER_GET_TRANSACTION_COUNT';
export const PROVIDER_JSON_RPC_SIGNER_SEND_TRANSACTION =
  'PROVIDER_JSON_RPC_SIGNER_SEND_TRANSACTION';
export const PROVIDER_JSON_RPC_SIGNER_SIGN_MESSAGE =
  'PROVIDER_JSON_RPC_SIGNER_SIGN_MESSAGE';
export const PROVIDER_JSON_RPC_SIGNER_SIGN_UNLOCK =
  'PROVIDER_JSON_RPC_SIGNER_SIGN_UNLOCK';

/* --- Contracts --- */
export const INIT_CONTRACT_REQUEST = 'INIT_CONTRACT_REQUEST';
export const INIT_CONTRACT_SUCCESS = 'INIT_CONTRACT_SUCCESS';
export const INIT_CONTRACT_FAILURE = 'INIT_CONTRACT_FAILURE';

export const DEPLOY_CONTRACT_REQUEST = 'DEPLOY_CONTRACT_REQUEST';
export const DEPLOY_CONTRACT_SUCCESS = 'DEPLOY_CONTRACT_SUCCESS';
export const DEPLOY_CONTRACT_FAILURE = 'DEPLOY_CONTRACT_FAILURE';

export const DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST =
  'DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST';
export const DEPLOY_CONTRACT_FROM_BYTECODE_SUCCESS =
  'DEPLOY_CONTRACT_FROM_BYTECODE_SUCCESS';
export const DEPLOY_CONTRACT_FROM_BYTECODE_FAILURE =
  'DEPLOY_CONTRACT_FROM_BYTECODE_FAILURE';
