// * Set Actions
export const SET_PROVIDER = 'SET_PROVIDER';
export const SET_PROVIDER_STATUS = 'SET_PROVIDER_STATUS';

export const ENABLE_REQUEST = 'ENABLE_REQUEST';
export const ENABLE_SUCCESS = 'ENABLE_SUCCESS';
export const ENABLE_FAILURE = 'ENABLE_FAILURE';

// * Init actions
export const INIT_CONTRACT_REQUEST = 'INIT_CONTRACT_REQUEST';
export const INIT_CONTRACT_SUCCESS = 'INIT_CONTRACT_SUCCESS';
export const INIT_CONTRACT_FAILURE = 'INIT_CONTRACT_FAILURE';

// * Deploy actions
export const DEPLOY_CONTRACT_REQUEST = 'DEPLOY_CONTRACT_REQUEST';
export const DEPLOY_CONTRACT_SUCCESS = 'DEPLOY_CONTRACT_SUCCESS';
export const DEPLOY_CONTRACT_FAILURE = 'DEPLOY_CONTRACT_FAILURE';

export const DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST =
  'DEPLOY_CONTRACT_FROM_BYTECODE_REQUEST';
export const DEPLOY_CONTRACT_FROM_BYTECODE_SUCCESS =
  'DEPLOY_CONTRACT_FROM_BYTECODE_SUCCESS';
export const DEPLOY_CONTRACT_FROM_BYTECODE_FAILURE =
  'DEPLOY_CONTRACT_FROM_BYTECODE_FAILURE';

// * Sign actions
export const SIGN_TYPED_MESSAGE_REQUEST = 'SIGN_TYPED_MESSAGE_REQUEST';
export const SIGN_TYPED_MESSAGE_SUCCESS = 'SIGN_TYPED_MESSAGE_SUCCESS';
export const SIGN_TYPED_MESSAGE_FAILURE = 'SIGN_TYPED_MESSAGE_FAILURE';
export const SIGN_MESSAGE_REQUEST = 'SIGN_MESSAGE';
export const SIGN_MESSAGE_SUCCESS = 'SIGN_MESSAGE_SUCCESS';
export const SIGN_MESSAGE_FAILURE = 'SIGN_MESSAGE_FAILURE';

export const SIGN_TRANSACTION_REQUEST = 'SIGN_TRANSACTION_REQUEST';
export const SIGN_TRANSACTION_SUCCESS = 'SIGN_TRANSACTION_SUCCESS';
export const SIGN_TRANSACTION_FAILURE = 'SIGN_TRANSACTION_FAILURE';

export const SEND_TRANSACTION_REQUEST = 'SEND_TRANSACTION_REQUEST';
export const SEND_TRANSACTION_SUCCESS = 'SEND_TRANSACTION_SUCCESS';
export const SEND_TRANSACTION_FAILURE = 'SEND_TRANSACTION_FAILURE';

// * Wallet
export const SET_WALLET = 'SET_WALLET';
export const SET_ADDRESS = 'SET_ADDRESS';

const Action = {};

const ActionType = {
  SET_PROVIDER: 'SET_PROVIDER',
  SET_PROVIDER_STATUS: 'SET_PROVIDER_STATUS',
  INIT_CONTRACT: 'INIT_CONTRACT',
  DEPLOY_CONTRACT: 'DEPLOY_CONTRACT',
  SIGN_TYPED_MESSAGE: 'SIGN_TYPED_MESSAGE',
  SIGN_MESSAGE: 'SIGN_MESSAGE',
  SEND_TRANSACTION: 'SEND_TRANSACTION',
  SET_WALLET: 'SET_WALLET',
  SET_ADDRESS: 'SET_ADDRESS'
};

export { ActionType };
